name: one_stop_house_builder_app
description: One Stop House Builder - Fullstack demo
publish_to: 'none'
version: 0.0.1
environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  http: ^0.13.6
  socket_io_client: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
