import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'firebase_options.dart'; // generated by `flutterfire configure`

import 'screens/vendor_dashboard_screen.dart';
import 'screens/vendor_registration_screen.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  // Anonymous sign-in for demo (replace with proper auth later)
  await FirebaseAuth.instance.signInAnonymously();

  runApp(const ProviderScope(child: OneStopApp()));
}

class OneStopApp extends StatelessWidget {
  const OneStopApp({super.key});

  @override
  Widget build(BuildContext context) {
    final theme = ThemeData(
      useMaterial3: true,
      colorSchemeSeed: const Color(0xFF006E5B),
      inputDecorationTheme: const InputDecorationTheme(border: OutlineInputBorder()),
    );

    return MaterialApp(
      title: 'One Stop House Builder',
      theme: theme,
      debugShowCheckedModeBanner: false,
      routes: {
        '/': (_) => const VendorDashboardScreen(),
        VendorRegistrationScreen.route: (_) => const VendorRegistrationScreen(),
      },
      initialRoute: '/',
    );
  }
}
